d1
    d2
        d3
            d4
                d6
                    d7
                        d8
                            a5
                                b5
                                    c5
                                        e5
                                            f5
                                                g5
                                                    h5